/**
 * Scene assembly for the Neural Amp 3D view.
 *
 * Geometry comes from the glTF components in assets/models (generated by
 * scripts/generate-amp-models.js). This module loads those components, assigns
 * the procedurally generated PBR materials to their named material slots and
 * wires up the interactive parts (knobs, power switch, LED, display).
 */

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

import {
  GRILLE_RECT,
  PANEL_HARDWARE,
  PANEL_RECT,
  computeKnobPlacements,
  valueToRotationRad,
} from "./ampLayout.js";
import type { Amp3dThemePreset } from "./ampTheme.js";
import {
  createBackdropCanvas,
  createBrushedMetalCanvas,
  createClothTextures,
  createDisplayCanvas,
  createFloorFadeCanvas,
  createGrilleAlphaCanvas,
  createGrilleBaseCanvas,
  createGrilleGlowCanvas,
  createLeatherTextures,
  createLogoCanvas,
  createNormalFromImageCanvas,
  createPanelTexture,
  createTolexTextures,
  type PanelLabel,
} from "./ampTextures.js";

const MODEL_BASE_PATH = "assets/models/";

const MODEL_FILES = {
  head: "amp-head.gltf",
  knob: "amp-knob.gltf",
  toggle: "amp-switch.gltf",
  led: "amp-led.gltf",
  jack: "amp-jack.gltf",
  cabinet: "amp-cabinet.gltf",
} as const;

export type Amp3dModelName = keyof typeof MODEL_FILES;

const TOLEX_TILE_METRES = 0.085;
/**
 * Physical size the photographed tolex swatch covers. It is a much larger patch
 * than the procedural fallback tile, so it repeats far less often across the
 * cabinet (which is what keeps the photo from reading as an obvious tile).
 */
const TOLEX_IMAGE_TILE_METRES = 0.26;
const LEATHER_TILE_METRES = 0.04;
const METAL_TILE_METRES = 0.12;

const TOLEX_IMAGE_FILE = "amp-tolex-black.jpeg";

/**
 * Master switch for powered-on live motion (LCD marquee + peak-driven grille glow).
 * Hardcoded off for now to keep the view static and cheap; flip to true to restore.
 * Bypass/power transitions still animate independently of this flag.
 */
export const AMP3D_LIVE_ANIMATION_ENABLED = false;

/** Duration of the power on/off light ramp (LED, grille glow, display). */
const POWER_TRANSITION_SECONDS = 1;

/** Peak-driven glow stays within a modest band around the theme base intensity. */
const GLOW_LEVEL_MIN = 0.82;
const GLOW_LEVEL_MAX = 1.18;

const SWITCH_LEVER_ON_X = -0.32;
const SWITCH_LEVER_OFF_X = 0.32;
const LED_OFF_INTENSITY = 0.02;
const LED_LIGHT_ON_INTENSITY = 0.12;
const GLOW_OFF_INTENSITY = 0.02;
const DISPLAY_ON_EMISSIVE = 1.25;
const DISPLAY_OFF_EMISSIVE = 0.04;

function smoothstep(t: number): number {
  const x = Math.min(1, Math.max(0, t));
  return x * x * (3 - 2 * x);
}

const modelCache = new Map<Amp3dModelName, Promise<THREE.Group>>();

interface TolexSurface {
  image: HTMLImageElement;
  /** Null when the image could not be read back to derive a normal map. */
  normal: HTMLCanvasElement | null;
}

let tolexSurfacePromise: Promise<TolexSurface | null> | null = null;

function loadImageElement(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.crossOrigin = "anonymous";
    image.decoding = "async";
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error(`Failed to load amp texture "${url}"`));
    image.src = url;
  });
}

/**
 * Loads the photographed tolex once per page and derives its normal map.
 *
 * Resolves to null (rather than rejecting) if the image is unavailable so the
 * amp still builds with the procedural covering; a missing decorative texture
 * must never take the whole view down.
 */
async function loadTolexSurface(): Promise<TolexSurface | null> {
  if (!tolexSurfacePromise) {
    tolexSurfacePromise = loadImageElement(MODEL_BASE_PATH + TOLEX_IMAGE_FILE)
      .then((image) => {
        let normal: HTMLCanvasElement | null = null;
        try {
          normal = createNormalFromImageCanvas(image, 256, 3.4);
        } catch (error) {
          // Canvas read-back can fail (tainted canvas, tiny/odd image). The
          // albedo is still perfectly usable on its own.
          console.warn("Amp 3D: could not derive tolex normal map", error);
        }
        return { image, normal };
      })
      .catch((error: unknown) => {
        console.warn("Amp 3D: falling back to procedural tolex", error);
        tolexSurfacePromise = null;
        return null;
      });
  }
  return tolexSurfacePromise;
}

/**
 * Theme tint for the photographed tolex. The swatch is near black, so the raw
 * theme tint (also near black) would crush it; instead we keep the hue and push
 * the value up to a subtle multiplier.
 */
function tolexImageTint(tint: string): THREE.Color {
  const color = new THREE.Color(tint);
  const max = Math.max(color.r, color.g, color.b);
  if (max <= 0.001) {
    return new THREE.Color(0xffffff);
  }
  const normalized = color.clone().multiplyScalar(1 / max);
  return new THREE.Color(0xffffff).lerp(normalized, 0.3);
}

let sharedLoader: GLTFLoader | null = null;

function getLoader(): GLTFLoader {
  if (!sharedLoader) {
    sharedLoader = new GLTFLoader();
    sharedLoader.setPath(MODEL_BASE_PATH);
  }
  return sharedLoader;
}

/** Loads (and caches) a glTF component, returning a fresh clone each call. */
export async function loadAmpComponent(name: Amp3dModelName): Promise<THREE.Group> {
  let entry = modelCache.get(name);
  if (!entry) {
    entry = getLoader()
      .loadAsync(MODEL_FILES[name])
      .then((gltf) => gltf.scene)
      .catch((error: unknown) => {
        // Do not cache failures: a transient load error should be retryable.
        modelCache.delete(name);
        throw error instanceof Error
          ? new Error(`Failed to load amp model "${MODEL_FILES[name]}": ${error.message}`)
          : new Error(`Failed to load amp model "${MODEL_FILES[name]}"`);
      });
    modelCache.set(name, entry);
  }
  const source = await entry;
  return source.clone(true);
}

export interface Amp3dKnobSpec {
  key: string;
  label: string;
  subLabel?: string;
  value: number;
  defaultValue?: number;
  min: number;
  max: number;
  step?: number;
  unit: string;
}

export interface Amp3dSceneOptions {
  knobs: Amp3dKnobSpec[];
  /** Text shown on the front grille (usually the effect display name). */
  logoText: string;
  /** Text shown on the control-panel display (usually the loaded model). */
  displayText: string;
  /** Small print to the right of the power switch. */
  brandText: string;
  bypassed: boolean;
  showCabinet: boolean;
  preset: Amp3dThemePreset;
}

interface KnobInstance {
  spec: Amp3dKnobSpec;
  root: THREE.Group;
  meshes: THREE.Object3D[];
}

function canvasTexture(
  source: HTMLCanvasElement | HTMLImageElement,
  {
    srgb = false,
    repeat = 0,
    // 4× is enough for this viewing distance; higher values burn fill-rate on
    // every shaded fragment for little visible gain inside the plugin panel.
    anisotropy = 4,
    wrapS,
    wrapT,
  }: {
    srgb?: boolean;
    repeat?: number;
    anisotropy?: number;
    wrapS?: THREE.Wrapping;
    wrapT?: THREE.Wrapping;
  } = {},
): THREE.Texture {
  const texture = new THREE.Texture(source);
  texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  texture.anisotropy = anisotropy;
  if (repeat > 0) {
    texture.wrapS = wrapS ?? THREE.RepeatWrapping;
    texture.wrapT = wrapT ?? THREE.RepeatWrapping;
    texture.repeat.set(repeat, repeat);
  } else {
    texture.wrapS = wrapS ?? THREE.ClampToEdgeWrapping;
    texture.wrapT = wrapT ?? THREE.ClampToEdgeWrapping;
  }
  texture.needsUpdate = true;
  return texture;
}

/**
 * Builds and owns the 3D amp. Everything created here is tracked so `dispose`
 * can release GPU resources when the effect panel is torn down.
 */
export class AmpScene {
  readonly scene = new THREE.Scene();
  readonly root = new THREE.Group();

  private readonly materials = new Map<string, THREE.Material>();
  private readonly textures: THREE.Texture[] = [];
  private readonly geometries = new Set<THREE.BufferGeometry>();
  private readonly knobs: KnobInstance[] = [];
  private readonly lights: THREE.Light[] = [];

    private switchLever: THREE.Object3D | null = null;
    private ledMaterial: THREE.MeshStandardMaterial | null = null;
    private glowMaterial: THREE.MeshStandardMaterial | null = null;
    private displayMaterial: THREE.MeshStandardMaterial | null = null;
    private displayTexture: THREE.Texture | null = null;
  private panelMaterial: THREE.MeshStandardMaterial | null = null;
  private ledLight: THREE.PointLight | null = null;
  private shadowMaterial: THREE.ShadowMaterial | null = null;
  private floorMesh: THREE.Mesh | null = null;
  private contactShadowMesh: THREE.Mesh | null = null;
  private headGroup: THREE.Group | null = null;
  private glowBaseIntensity = 0;
  /** Normalised node output peak (0..1), used to vary grille glow a little. */
  private signalLevel = 0;
  private switchHitTargets: THREE.Object3D[] = [];
  private environmentTexture: THREE.Texture | null = null;
    /** UV units/sec for the front-panel LCD marquee (applied via texture.offset). */
    private static readonly DISPLAY_SCROLL_SPEED = 0.12;
    /**
     * 0 = fully off/bypassed, 1 = fully powered. Animated over
     * {@link POWER_TRANSITION_SECONDS} when the user toggles bypass.
     */
    private powerAmount = 0;
    private powerTarget = 0;
    private powerTransitionActive = false;
    /** Last `update(elapsedSeconds)` sample, used to integrate the power ramp. */
    private lastElapsedSeconds: number | null = null;

  private options: Amp3dSceneOptions;
  private disposed = false;

  private constructor(options: Amp3dSceneOptions) {
    this.options = options;
    this.scene.add(this.root);
  }

  static async create(options: Amp3dSceneOptions, renderer: THREE.WebGLRenderer): Promise<AmpScene> {
    const instance = new AmpScene(options);
    await instance.build(renderer);
    return instance;
  }

  private async build(renderer: THREE.WebGLRenderer): Promise<void> {
    const tolexSurface = await loadTolexSurface();
    this.buildMaterials(tolexSurface);
    this.buildEnvironment(renderer);
    this.buildBackground();
    this.buildLights();

    const [head, cabinet] = await Promise.all([
      loadAmpComponent("head"),
      this.options.showCabinet ? loadAmpComponent("cabinet") : Promise.resolve(null),
    ]);

    const headGroup = new THREE.Group();
    headGroup.name = "AmpHead";
    this.applyMaterials(head);
    headGroup.add(head);

    await this.addPanelHardware(headGroup);
    this.addLogoDecal(headGroup);

    if (cabinet) {
      this.applyMaterials(cabinet);
      // Stack from the measured geometry so the cabinet rests on the floor and
      // the head sits flush on the cabinet, whatever the model dimensions are.
      const cabinetBounds = new THREE.Box3().setFromObject(cabinet);
      cabinet.position.y = -cabinetBounds.min.y;
      this.root.add(cabinet);

      const headBounds = new THREE.Box3().setFromObject(headGroup);
      headGroup.position.y = (cabinetBounds.max.y - cabinetBounds.min.y) - headBounds.min.y;
    } else {
      const headBounds = new THREE.Box3().setFromObject(headGroup);
      headGroup.position.y = -headBounds.min.y;
    }

    this.root.add(headGroup);
    this.headGroup = headGroup;
    this.addFloor();
    this.addContactShadow();
        // Initial mount snaps to the current bypass state (no fade-in on load).
        this.snapPowerState();
      }

  /**
   * Soft elliptical contact shadow under the rig. The directional key light is
   * in front of the amp, so its cast shadow falls behind it; without this the
   * amp reads as floating above the floor.
   */
  private addContactShadow(): void {
    const bounds = this.getContentBounds();
    if (bounds.isEmpty()) {
      return;
    }
    const size = new THREE.Vector3();
    const center = new THREE.Vector3();
    bounds.getSize(size);
    bounds.getCenter(center);

    const geometry = new THREE.PlaneGeometry(size.x * 1.9, Math.max(size.z, 0.26) * 3.2);
    this.geometries.add(geometry);
    const material = new THREE.MeshBasicMaterial({
      color: 0x000000,
      transparent: true,
      opacity: Math.min(0.9, this.options.preset.shadowOpacity * 1.5),
      alphaMap: this.trackTexture(canvasTexture(createFloorFadeCanvas())),
      depthWrite: false,
    });
    this.materials.set("ContactShadow", material);
    const mesh = new THREE.Mesh(geometry, material);
    mesh.name = "ContactShadow";
    mesh.rotation.x = -Math.PI / 2;
    mesh.position.set(center.x, 0.0015, center.z);
    mesh.renderOrder = 1;
    this.contactShadowMesh = mesh;
    this.root.add(mesh);
  }

  // ── Materials ────────────────────────────────────────────────────────────

  private track<T extends THREE.Material>(name: string, material: T): T {
    this.materials.set(name, material);
    return material;
  }

  private trackTexture(texture: THREE.Texture): THREE.Texture {
    this.textures.push(texture);
    return texture;
  }

    /** Swap a live map without leaking the previous entry in the track list. */
    private replaceTrackedTexture(
      previous: THREE.Texture | null | undefined,
      next: THREE.Texture,
    ): THREE.Texture {
      if (previous) {
        const index = this.textures.indexOf(previous);
        if (index >= 0) {
          this.textures.splice(index, 1);
        }
        previous.dispose();
      }
      return this.trackTexture(next);
    }

  /** Photographed tolex covering used for the head shell, frame and cabinet. */
  private buildImageTolexMaterial(
    surface: TolexSurface,
    preset: Amp3dThemePreset,
  ): THREE.MeshStandardMaterial {
    const repeat = 1 / TOLEX_IMAGE_TILE_METRES;
    const material = new THREE.MeshStandardMaterial({
          map: this.trackTexture(canvasTexture(surface.image, { srgb: true, repeat, anisotropy: 8 })),
      color: tolexImageTint(preset.tolexTint),
      roughness: 0.82,
      metalness: 0.0,
    });
    if (surface.normal) {
      material.normalMap = this.trackTexture(canvasTexture(surface.normal, { repeat }));
      material.normalScale = new THREE.Vector2(0.7, 0.7);
    }
    return material;
  }

  /** Fallback covering when the tolex photo cannot be loaded. */
  private buildProceduralTolexMaterial(preset: Amp3dThemePreset): THREE.MeshStandardMaterial {
    const tolex = createTolexTextures(preset.tolexTint);
    const repeat = 1 / TOLEX_TILE_METRES;
    return new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(tolex.albedo, { srgb: true, repeat })),
      normalMap: this.trackTexture(canvasTexture(tolex.normal, { repeat })),
      normalScale: new THREE.Vector2(0.85, 0.85),
      roughness: 0.86,
      metalness: 0.0,
    });
  }

  private buildMaterials(tolexSurface: TolexSurface | null): void {
    const preset = this.options.preset;

    this.track("Tolex", tolexSurface
      ? this.buildImageTolexMaterial(tolexSurface, preset)
      : this.buildProceduralTolexMaterial(preset));

    const leather = createLeatherTextures(preset.tolexTint);
    const leatherRepeat = 1 / LEATHER_TILE_METRES;
    this.track("Leather", new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(leather.albedo, { srgb: true, repeat: leatherRepeat })),
      normalMap: this.trackTexture(canvasTexture(leather.normal, { repeat: leatherRepeat })),
      roughness: 0.72,
      metalness: 0.0,
    }));

    const panelBody = createBrushedMetalCanvas(256, 256, preset.panelBase, preset.panelTint, 0x51de);
    this.track("PanelBody", new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(panelBody, { srgb: true, repeat: 1 / METAL_TILE_METRES })),
      roughness: 0.38,
      metalness: 0.85,
    }));

    this.panelMaterial = this.track("PanelFace", new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(this.buildPanelCanvas(), { srgb: true })),
      roughness: 0.34,
      metalness: 0.78,
    }));

    this.track("GrilleMetal", new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(createGrilleBaseCanvas(), { srgb: true })),
      alphaMap: this.trackTexture(canvasTexture(createGrilleAlphaCanvas())),
      alphaTest: 0.5,
      roughness: 0.45,
      metalness: 0.9,
      side: THREE.DoubleSide,
    }));

    this.track("GrilleBacking", new THREE.MeshStandardMaterial({
      color: 0x090a0c,
      roughness: 0.95,
      metalness: 0.0,
    }));

    this.glowBaseIntensity = this.options.bypassed ? GLOW_OFF_INTENSITY : preset.grilleGlowIntensity;
        this.glowMaterial = this.track("GrilleGlow", new THREE.MeshStandardMaterial({
          color: 0x000000,
          emissive: new THREE.Color(preset.grilleGlowColor),
          emissiveMap: this.trackTexture(canvasTexture(
            createGrilleGlowCanvas(`#${new THREE.Color(preset.grilleGlowColor).getHexString()}`, !this.options.bypassed),
            { srgb: true },
          )),
          emissiveIntensity: this.glowBaseIntensity,
          roughness: 1,
          metalness: 0,
        }));

    const cloth = createClothTextures(preset.tolexTint === "#2a221d" ? "#3a352f" : "#221f1c");
    this.track("GrilleCloth", new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(cloth.albedo, { srgb: true, repeat: 1 / 0.06 })),
      normalMap: this.trackTexture(canvasTexture(cloth.normal, { repeat: 1 / 0.06 })),
      roughness: 0.94,
      metalness: 0.0,
      // Real grille cloth is a loose weave: the speakers behind it stay faintly
      // visible instead of the baffle reading as a flat panel.
      transparent: true,
      opacity: 0.88,
      depthWrite: false,
    }));

    this.track("ChromeTrim", new THREE.MeshStandardMaterial({
      color: 0xc9ccd2,
      roughness: 0.18,
      metalness: 1.0,
    }));
    this.track("CornerMetal", new THREE.MeshStandardMaterial({
      color: 0x101214,
      roughness: 0.45,
      metalness: 1.0,
    }));
    this.track("LogoPlate", new THREE.MeshStandardMaterial({
      color: 0xdfe3ea,
      roughness: 0.24,
      metalness: 1.0,
    }));

    this.displayTexture = this.trackTexture(this.createDisplayTexture());
        this.displayMaterial = this.track("DisplayGlass", new THREE.MeshStandardMaterial({
          color: 0x05070a,
          emissive: new THREE.Color(0xffffff),
          emissiveMap: this.displayTexture,
          emissiveIntensity: this.options.bypassed ? DISPLAY_OFF_EMISSIVE : DISPLAY_ON_EMISSIVE,
          roughness: 0.16,
          metalness: 0.0,
        }));

    this.track("KnobBody", new THREE.MeshStandardMaterial({
      color: 0x121316,
      roughness: 0.58,
      metalness: 0.05,
    }));
    this.track("KnobCap", new THREE.MeshStandardMaterial({
      color: 0xeeeff2,
      roughness: 0.32,
      metalness: 0.0,
    }));
    this.track("KnobPointer", new THREE.MeshStandardMaterial({
      color: 0x050607,
      roughness: 0.42,
      metalness: 0.0,
    }));

    this.ledMaterial = this.track("LedLens", new THREE.MeshStandardMaterial({
      color: 0x0a1024,
      emissive: new THREE.Color(preset.ledColor),
          emissiveIntensity: this.options.bypassed ? LED_OFF_INTENSITY : preset.ledIntensity,
      roughness: 0.08,
      metalness: 0.0,
    }));

    this.track("Rubber", new THREE.MeshStandardMaterial({
      color: 0x0b0b0d,
      roughness: 0.95,
      metalness: 0.0,
    }));
    this.track("SpeakerCone", new THREE.MeshStandardMaterial({
      color: 0x1a1613,
      roughness: 0.9,
      metalness: 0.0,
      side: THREE.DoubleSide,
    }));
    this.track("SpeakerDust", new THREE.MeshStandardMaterial({
      color: 0x121316,
      roughness: 0.6,
      metalness: 0.25,
    }));
  }

  private buildPanelCanvas(): HTMLCanvasElement {
    const placements = computeKnobPlacements(this.options.knobs.length);
    const labels: PanelLabel[] = this.options.knobs.map((knob, index) => ({
      placement: placements[index],
      topLabel: knob.label,
      bottomLabel: knob.subLabel,
    }));
    return createPanelTexture({
      labels,
      brandText: this.options.brandText,
      panelBase: this.options.preset.panelBase,
      panelTint: this.options.preset.panelTint,
      textColor: this.options.preset.panelText,
      mutedTextColor: this.options.preset.panelTextMuted,
    });
  }

  /**
   * Replaces the placeholder glTF materials with the generated PBR set, using
   * the `materialSlot` extras written by the model generator (falling back to
   * the glTF material name).
     *
     * Small hardware (knobs, switch, LED, jack) should pass `castShadow: false` —
     * their contribution to the key-light shadow map is invisible at this scale
     * but still costs a full shadow pass per mesh.
     */
    private applyMaterials(object: THREE.Object3D, { castShadow = true }: { castShadow?: boolean } = {}): void {
      object.traverse((child) => {
        const mesh = child as THREE.Mesh;
        if (!mesh.isMesh) {
          return;
        }

        const slot = typeof mesh.userData?.materialSlot === "string"
          ? mesh.userData.materialSlot
          : (Array.isArray(mesh.material) ? mesh.material[0]?.name : mesh.material?.name) ?? "";
        const replacement = this.materials.get(slot);
        if (replacement) {
          mesh.material = replacement;
        }

        const material = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
        const transparent = Boolean(material && "transparent" in material && material.transparent);
        // Transparent surfaces still receive light but casting them is expensive
        // and usually wrong (alpha-tested grille is handled separately).
        mesh.castShadow = castShadow && !transparent;
        mesh.receiveShadow = true;
        // The cloned glTF materials are no longer referenced; release them now.
        // (Geometry is shared with the cache and must not be disposed here.)
      });
    }

  // ── Panel hardware ───────────────────────────────────────────────────────

  private async addPanelHardware(headGroup: THREE.Group): Promise<void> {
    const [knobTemplate, toggle, led, jack] = await Promise.all([
      loadAmpComponent("knob"),
      loadAmpComponent("toggle"),
      loadAmpComponent("led"),
      loadAmpComponent("jack"),
    ]);

    const placements = computeKnobPlacements(this.options.knobs.length);
    this.options.knobs.forEach((spec, index) => {
      const placement = placements[index];
      const knobRoot = index === 0 ? knobTemplate : knobTemplate.clone(true);
          this.applyMaterials(knobRoot);
      const holder = new THREE.Group();
      holder.name = `Knob_${spec.key}`;
      holder.position.set(placement.x, placement.y, PANEL_RECT.faceZ);
      holder.rotation.z = -valueToRotationRad(spec.value, spec.min, spec.max);
      holder.add(knobRoot);
      headGroup.add(holder);

      const meshes: THREE.Object3D[] = [];
      holder.traverse((child) => {
        if ((child as THREE.Mesh).isMesh) {
          child.userData.knobKey = spec.key;
          meshes.push(child);
        }
      });
      this.knobs.push({ spec, root: holder, meshes });
    });

        this.applyMaterials(toggle, { castShadow: false });
    toggle.position.set(PANEL_HARDWARE.powerSwitch.x, PANEL_HARDWARE.powerSwitch.y, PANEL_RECT.faceZ);
    headGroup.add(toggle);
    this.switchLever = toggle.getObjectByName("SwitchLever") ?? null;
    this.switchHitTargets = [];
    toggle.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        child.userData.powerSwitch = true;
        this.switchHitTargets.push(child);
      }
    });

        this.applyMaterials(led, { castShadow: false });
    led.position.set(PANEL_HARDWARE.powerLed.x, PANEL_HARDWARE.powerLed.y, PANEL_RECT.faceZ);
    headGroup.add(led);
    led.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        child.userData.powerSwitch = true;
        this.switchHitTargets.push(child);
      }
    });

    this.ledLight = new THREE.PointLight(this.options.preset.ledColor, 0, 0.12, 2);
    this.ledLight.position.set(PANEL_HARDWARE.powerLed.x, PANEL_HARDWARE.powerLed.y, PANEL_RECT.faceZ + 0.012);
    headGroup.add(this.ledLight);

        this.applyMaterials(jack, { castShadow: false });
    jack.position.set(PANEL_HARDWARE.jack.x, PANEL_HARDWARE.jack.y, PANEL_RECT.faceZ);
    headGroup.add(jack);
  }

  /** Brushed logo decal floating just in front of the grille. */
  private addLogoDecal(headGroup: THREE.Group): void {
    const width = 0.26;
    const geometry = new THREE.PlaneGeometry(width, width / 4);
    this.geometries.add(geometry);
    const logoCanvas = createLogoCanvas(this.options.logoText);
    const material = new THREE.MeshStandardMaterial({
      map: this.trackTexture(canvasTexture(logoCanvas, { srgb: true })),
      alphaMap: this.trackTexture(canvasTexture(logoCanvas)),
      transparent: true,
      roughness: 0.25,
      metalness: 0.9,
      depthWrite: false,
    });
    this.materials.set("LogoDecal", material);
    const mesh = new THREE.Mesh(geometry, material);
    mesh.position.set(
      0,
      (GRILLE_RECT.top + GRILLE_RECT.bottom) / 2,
      GRILLE_RECT.faceZ + 0.0025,
    );
    mesh.castShadow = false;
    headGroup.add(mesh);
  }

  private addFloor(): void {
    const preset = this.options.preset;
    const geometry = new THREE.PlaneGeometry(14, 14);
    this.geometries.add(geometry);

    // A real surface (rather than a bare shadow catcher) grounds the amp and
    // picks up the environment reflection. It fades out radially so the plane
    // edge never shows against the backdrop.
    const material = new THREE.MeshStandardMaterial({
      color: preset.floorColor,
      roughness: 0.42,
      metalness: 0.05,
      transparent: true,
      alphaMap: this.trackTexture(canvasTexture(createFloorFadeCanvas())),
      depthWrite: false,
    });
    this.materials.set("Floor", material);
    const floor = new THREE.Mesh(geometry, material);
    floor.name = "Floor";
    floor.rotation.x = -Math.PI / 2;
    floor.position.y = -0.001;
    floor.receiveShadow = true;
    floor.castShadow = false;
    this.floorMesh = floor;
    this.root.add(floor);
  }

  private buildBackground(): void {
    const preset = this.options.preset;
    const canvas = createBackdropCanvas(
      `#${new THREE.Color(preset.backgroundTop).getHexString()}`,
      `#${new THREE.Color(preset.backgroundBottom).getHexString()}`,
    );
    const texture = this.trackTexture(canvasTexture(canvas, { srgb: true }));
    texture.wrapS = THREE.ClampToEdgeWrapping;
    texture.wrapT = THREE.ClampToEdgeWrapping;
    this.scene.background = texture;
  }

  // ── Lighting / environment ───────────────────────────────────────────────

  private buildEnvironment(renderer: THREE.WebGLRenderer): void {
    const pmrem = new THREE.PMREMGenerator(renderer);
    const environment = new RoomEnvironment();
    this.environmentTexture = pmrem.fromScene(environment, 0.04).texture;
    this.scene.environment = this.environmentTexture;
    this.scene.environmentIntensity = this.options.preset.environmentIntensity;
    environment.dispose?.();
    pmrem.dispose();
  }

  private buildLights(): void {
    const preset = this.options.preset;

    const ambient = new THREE.HemisphereLight(preset.ambientColor, 0x101012, preset.ambientIntensity);
    this.scene.add(ambient);
    this.lights.push(ambient);

    const key = new THREE.DirectionalLight(preset.key.color, preset.key.intensity);
    key.position.set(...preset.key.position);
    key.castShadow = true;
        // 512² is plenty for a small amp in a panel; 1024² quadrupled shadow cost.
        key.shadow.mapSize.set(512, 512);
        key.shadow.camera.near = 0.1;
        key.shadow.camera.far = 6;
        key.shadow.camera.left = -1.2;
        key.shadow.camera.right = 1.2;
        key.shadow.camera.top = 2.2;
        key.shadow.camera.bottom = -0.4;
        key.shadow.bias = -0.0012;
        key.shadow.normalBias = 0.012;
    this.scene.add(key);
    this.lights.push(key);

    const fill = new THREE.DirectionalLight(preset.fill.color, preset.fill.intensity);
    fill.position.set(...preset.fill.position);
    this.scene.add(fill);
    this.lights.push(fill);

    const rim = new THREE.DirectionalLight(preset.rim.color, preset.rim.intensity);
    rim.position.set(...preset.rim.position);
    this.scene.add(rim);
    this.lights.push(rim);
  }

  // ── Public API ───────────────────────────────────────────────────────────

  get knobHitTargets(): THREE.Object3D[] {
    return this.knobs.flatMap((knob) => knob.meshes);
  }

  get powerHitTargets(): THREE.Object3D[] {
    return this.switchHitTargets;
  }

  getKnobSpec(key: string): Amp3dKnobSpec | undefined {
    return this.knobs.find((knob) => knob.spec.key === key)?.spec;
  }

  setKnobValue(key: string, value: number): void {
    const knob = this.knobs.find((entry) => entry.spec.key === key);
    if (!knob) {
      return;
    }
    knob.spec.value = value;
    knob.root.rotation.z = -valueToRotationRad(value, knob.spec.min, knob.spec.max);
  }

  /**
     * @param bypassed New bypass flag.
     * @param immediate When true (e.g. prefers-reduced-motion), snap with no fade.
     */
    setBypassed(bypassed: boolean, immediate = false): void {
      if (this.options.bypassed === bypassed) {
        return;
      }
      this.options.bypassed = bypassed;
      if (immediate) {
        this.snapPowerState();
      } else {
        this.beginPowerTransition();
      }
  }

    setDisplayText(text: string): void {
      if (this.options.displayText === text) {
        return;
      }
      this.options.displayText = text;
      // Keep the lit artwork while any power is showing so the fade stays smooth.
      this.refreshDisplayTexture(this.powerAmount > 0.001 || !this.options.bypassed);
    }

    /** Instantly match visuals to the current bypass flag (scene build / reduced motion). */
    private snapPowerState(): void {
      this.powerTarget = this.options.bypassed ? 0 : 1;
      this.powerAmount = this.powerTarget;
      this.powerTransitionActive = false;
      this.lastElapsedSeconds = null;
      this.refreshGlowTexture(this.powerAmount > 0.5);
      this.refreshDisplayTexture(this.powerAmount > 0.5);
      this.applyPowerVisuals();
    }

    /** Start a 1s ramp toward the current bypass target. */
    private beginPowerTransition(): void {
      this.powerTarget = this.options.bypassed ? 0 : 1;
      this.lastElapsedSeconds = null;
      if (Math.abs(this.powerAmount - this.powerTarget) < 1e-4) {
        this.snapPowerState();
        return;
      }
      // Powering up: swap in lit maps immediately so the ramp has something to reveal.
      if (this.powerTarget > this.powerAmount) {
        this.refreshGlowTexture(true);
        this.refreshDisplayTexture(true);
      }
      this.powerTransitionActive = true;
      this.applyPowerVisuals();
    }

    /**
     * Applies the current `powerAmount` to LED, point light, grille glow, display
     * and the rocker switch. Cheap uniform updates only — no texture rebuilds.
     */
    private applyPowerVisuals(): void {
      const t = smoothstep(this.powerAmount);
      const preset = this.options.preset;

      if (this.switchLever) {
        this.switchLever.rotation.x = THREE.MathUtils.lerp(SWITCH_LEVER_OFF_X, SWITCH_LEVER_ON_X, t);
      }
      if (this.ledMaterial) {
        this.ledMaterial.emissiveIntensity = THREE.MathUtils.lerp(
          LED_OFF_INTENSITY,
          preset.ledIntensity,
          t,
        );
      }
      if (this.ledLight) {
        this.ledLight.intensity = THREE.MathUtils.lerp(0, LED_LIGHT_ON_INTENSITY, t);
      }
      if (this.displayMaterial) {
        this.displayMaterial.emissiveIntensity = THREE.MathUtils.lerp(
          DISPLAY_OFF_EMISSIVE,
          DISPLAY_ON_EMISSIVE,
          t,
        );
      }

      this.glowBaseIntensity = THREE.MathUtils.lerp(
        GLOW_OFF_INTENSITY,
        preset.grilleGlowIntensity,
        t,
      );
      this.applyGlowIntensity();
    }

    /**
     * Sets the current node output level used to modulate grille glow.
     * `level` is expected in 0..1 (already peak-averaged / normalised by the UI).
     * @returns true when the glow actually changed (callers should re-render).
     */
    setSignalLevel(level: number): boolean {
      if (!AMP3D_LIVE_ANIMATION_ENABLED) {
        return false;
      }
      const next = Number.isFinite(level) ? THREE.MathUtils.clamp(level, 0, 1) : 0;
      // Glow only spans ~±18% of base intensity; sub-percent level noise is invisible
      // but diagnostics arrive many times per second and used to force full redraws.
      if (Math.abs(next - this.signalLevel) < 0.02) {
        return false;
      }
      this.signalLevel = next;
      this.applyGlowIntensity();
      return true;
    }

    private applyGlowIntensity(): void {
      if (!this.glowMaterial) {
        return;
      }
      if (this.powerAmount <= 0.001 || !AMP3D_LIVE_ANIMATION_ENABLED) {
        this.glowMaterial.emissiveIntensity = this.glowBaseIntensity;
        return;
      }
      // Quiet signal sits slightly under the theme base; louder peaks lift it a little.
      const scale = GLOW_LEVEL_MIN + (GLOW_LEVEL_MAX - GLOW_LEVEL_MIN) * this.signalLevel;
      this.glowMaterial.emissiveIntensity = this.glowBaseIntensity * scale;
    }

    /** True while a short power ramp is in flight. */
    get isPowerTransitioning(): boolean {
      return !this.disposed && this.powerTransitionActive;
    }

    /**
     * True while the scene has motion to draw: a power on/off ramp, or (when
     * enabled) the powered-on idle marquee / reactive glow.
     */
    get isAnimated(): boolean {
      if (this.disposed) {
        return false;
      }
      if (this.powerTransitionActive) {
        return true;
      }
      if (!AMP3D_LIVE_ANIMATION_ENABLED) {
        return false;
      }
      return !this.options.bypassed;
    }

    /**
     * Advances time-based motion: power on/off ramps, and (when enabled) the
     * front-panel display marquee.
     *
     * Marquee motion is a UV offset only — no canvas redraw, no texture upload.
     */
    update(elapsedSeconds: number): void {
      if (this.disposed) {
        return;
      }

      if (this.powerTransitionActive) {
        if (this.lastElapsedSeconds === null) {
          this.lastElapsedSeconds = elapsedSeconds;
        } else {
          const dt = Math.max(0, Math.min(0.05, elapsedSeconds - this.lastElapsedSeconds));
          this.lastElapsedSeconds = elapsedSeconds;
          const delta = dt / POWER_TRANSITION_SECONDS;
          if (this.powerAmount < this.powerTarget) {
            this.powerAmount = Math.min(this.powerTarget, this.powerAmount + delta);
          } else if (this.powerAmount > this.powerTarget) {
            this.powerAmount = Math.max(this.powerTarget, this.powerAmount - delta);
          }
          this.applyPowerVisuals();
          if (Math.abs(this.powerAmount - this.powerTarget) < 1e-4) {
            this.powerAmount = this.powerTarget;
            this.powerTransitionActive = false;
            this.lastElapsedSeconds = null;
            // Dim maps once fully off so a cold amp does not keep lit artwork at ε intensity.
            if (this.powerAmount <= 0) {
              this.refreshGlowTexture(false);
              this.refreshDisplayTexture(false);
              this.applyPowerVisuals();
            }
          }
        }
      }

      if (
        AMP3D_LIVE_ANIMATION_ENABLED
        && !this.options.bypassed
        && this.displayTexture
        && this.powerAmount > 0.001
      ) {
        // Positive offset scrolls text right-to-left like a classic LCD marquee.
        const offset = (elapsedSeconds * AmpScene.DISPLAY_SCROLL_SPEED) % 1;
        this.displayTexture.offset.x = offset;
      }
    }

    /** Untracked display map — callers must `trackTexture` / `replaceTrackedTexture`. */
      private createDisplayTexture(active = !this.options.bypassed): THREE.Texture {
        const canvas = createDisplayCanvas(
          this.options.displayText,
          this.options.preset.displayColor,
          active,
        );
        // Repeat on S so offset.x marquee-scrolls without regenerating pixels.
        return canvasTexture(canvas, {
          srgb: true,
          wrapS: THREE.RepeatWrapping,
          wrapT: THREE.ClampToEdgeWrapping,
        });
      }

      private refreshGlowTexture(active = !this.options.bypassed): void {
        if (!this.glowMaterial) {
          return;
        }
        const color = `#${new THREE.Color(this.options.preset.grilleGlowColor).getHexString()}`;
        const canvas = createGrilleGlowCanvas(color, active);
        const texture = canvasTexture(canvas, { srgb: true });
        this.glowMaterial.emissiveMap = this.replaceTrackedTexture(this.glowMaterial.emissiveMap, texture);
        this.glowMaterial.needsUpdate = true;
      }

      private refreshDisplayTexture(active = !this.options.bypassed): void {
        if (!this.displayMaterial) {
          return;
        }
        const previousOffsetX = this.displayTexture?.offset.x ?? 0;
        this.displayTexture = this.replaceTrackedTexture(this.displayTexture, this.createDisplayTexture(active));
        this.displayTexture.offset.x = previousOffsetX;
        this.displayMaterial.emissiveMap = this.displayTexture;
        this.displayMaterial.needsUpdate = true;
      }

  /** Bounding box of the amp (excluding the shadow-catching floor). */
  getContentBounds(): THREE.Box3 {
    const box = new THREE.Box3();
    this.root.children.forEach((child) => {
      if (child === this.floorMesh
        || child === this.contactShadowMesh
        || (child as THREE.Mesh).material === this.shadowMaterial) {
        return;
      }
      box.expandByObject(child);
    });
    return box;
  }

  /**
   * Bounds the camera should frame. With a cabinet the rig is far taller than
   * it is wide, so framing all of it shrinks the control panel to the point of
   * being unusable. Instead we frame the head and let the cabinet run off the
   * bottom of the viewport — it stays implied rather than fully in shot.
   */
  getFocusBounds(): THREE.Box3 {
    const content = this.getContentBounds();
    if (!this.headGroup || !this.options.showCabinet || content.isEmpty()) {
      return content;
    }
    const head = new THREE.Box3().setFromObject(this.headGroup);
    if (head.isEmpty()) {
      return content;
    }
    // Keep a sliver of the cabinet top in frame so the stack still reads as a
    // full rig, then clamp to the real content so we never frame empty space.
    head.min.y = Math.max(content.min.y, head.min.y - (head.max.y - head.min.y) * 0.45);
    head.min.x = Math.min(head.min.x, content.min.x);
    head.max.x = Math.max(head.max.x, content.max.x);
    return head;
  }

  dispose(): void {
    if (this.disposed) {
      return;
    }
    this.disposed = true;

    this.lights.forEach((light) => {
      light.parent?.remove(light);
      (light as unknown as { dispose?: () => void }).dispose?.();
    });
    this.lights.length = 0;

    this.materials.forEach((material) => material.dispose());
    this.materials.clear();
    this.textures.forEach((texture) => texture.dispose());
    this.textures.length = 0;
    this.geometries.forEach((geometry) => geometry.dispose());
    this.geometries.clear();
    this.environmentTexture?.dispose();
    this.environmentTexture = null;
        this.displayTexture = null;
        this.scene.environment = null;
        this.knobs.length = 0;
        this.switchHitTargets = [];
        this.scene.clear();
      }
    }
